version: "3.7"

services:
  salt-master-debian:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Debian-11-master
    container_name: salt-master-debian
    hostname: salt.master.debian
    volumes:
      - ..:/workspace:rw
      - ./master.d:/etc/salt/master.d:ro
      - ../salt:/srv/salt:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - salt-playground

  salt-minion-debian:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Debian-11-minion
    image: salt-minion-debian
    container_name: salt-minion-debian
    hostname: debian.salt.minion
    volumes:
      - ./minion.d/master.conf:/etc/salt/minion.d/master.conf:ro
      - ./minion.d/id-debian.conf:/etc/salt/minion.d/id.conf:ro
    networks:
      - salt-playground

  salt-minion-ubuntu:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Ubuntu-2204
    image: salt-minion-ubuntu
    container_name: salt-minion-ubuntu
    hostname: ubuntu.salt.minion
    volumes:
      - ./minion.d/master.conf:/etc/salt/minion.d/master.conf:ro
      - ./minion.d/id-ubuntu.conf:/etc/salt/minion.d/id.conf:ro
    networks:
      - salt-playground

  salt-minion-alma:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Alma-8
    image: salt-minion-alma
    container_name: salt-minion-alma
    hostname: alma.salt.minion
    volumes:
      - ./minion.d/master.conf:/etc/salt/minion.d/master.conf:ro
      - ./minion.d/id-alma.conf:/etc/salt/minion.d/id.conf:ro
    networks:
      - salt-playground

  salt-minion-suse:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-OpenSUSE-Leap-15
    image: salt-minion-suse
    container_name: salt-minion-suse
    hostname: suse.salt.minion
    volumes:
      - ./minion.d/master.conf:/etc/salt/minion.d/master.conf:ro
      - ./minion.d/id-suse.conf:/etc/salt/minion.d/id.conf:ro
    networks:
      - salt-playground

networks:
  salt-playground:
